export const loader = `
<div class="loadingio-spinner-spinner-78o7s0h5tl4"><div class="ldio-hp2wpoa2fsa">
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
</div></div>
<style type="text/css">
  @keyframes ldio-hp2wpoa2fsa {
    0% { opacity: 1 }
    100% { opacity: 0 }
  }
  .ldio-hp2wpoa2fsa div {
    left: 47px;
    top: 24px;
    position: absolute;
    animation: ldio-hp2wpoa2fsa linear 1s infinite;
    background: #93dbe9;
    width: 6px;
    height: 12px;
    border-radius: 2.52px / 2.52px;
    transform-origin: 3px 26px;
  }.ldio-hp2wpoa2fsa div:nth-child(1) {
    transform: rotate(0deg);
    animation-delay: -0.9s;
    background: #93dbe9;
  }.ldio-hp2wpoa2fsa div:nth-child(2) {
    transform: rotate(36deg);
    animation-delay: -0.8s;
    background: #93dbe9;
  }.ldio-hp2wpoa2fsa div:nth-child(3) {
    transform: rotate(72deg);
    animation-delay: -0.7s;
    background: #93dbe9;
  }.ldio-hp2wpoa2fsa div:nth-child(4) {
    transform: rotate(108deg);
    animation-delay: -0.6s;
    background: #93dbe9;
  }.ldio-hp2wpoa2fsa div:nth-child(5) {
    transform: rotate(144deg);
    animation-delay: -0.5s;
    background: #93dbe9;
  }.ldio-hp2wpoa2fsa div:nth-child(6) {
    transform: rotate(180deg);
    animation-delay: -0.4s;
    background: #93dbe9;
  }.ldio-hp2wpoa2fsa div:nth-child(7) {
    transform: rotate(216deg);
    animation-delay: -0.3s;
    background: #93dbe9;
  }.ldio-hp2wpoa2fsa div:nth-child(8) {
    transform: rotate(252deg);
    animation-delay: -0.2s;
    background: #93dbe9;
  }.ldio-hp2wpoa2fsa div:nth-child(9) {
    transform: rotate(288deg);
    animation-delay: -0.1s;
    background: #93dbe9;
  }.ldio-hp2wpoa2fsa div:nth-child(10) {
    transform: rotate(324deg);
    animation-delay: 0s;
    background: #93dbe9;
  }
  .loadingio-spinner-spinner-78o7s0h5tl4 {
    width: 100px;
    height: 100px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-hp2wpoa2fsa {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-hp2wpoa2fsa div { box-sizing: content-box; }
  /* generated by https://loading.io/ */
</style>
`